#!/usr/bin/env python3.7
import argparse

parser = argparse.ArgumentParser(description='Read a file in Reverse')
parser.add_argument('filename', help='File to read')
parser.add_argument('--limit', '-l', type=int, help='Number of lines to read')

args = parser.parse_args()

try:
    f = open(args.filename)
    limit = args.limit
except FileNotFoundError as err:
    print(f"Error: {err}")
else:
    with f:
        lines = f.readlines()
        lines.reverse()
        if limit:
            lines = lines[:args.limit]
        for line in lines:
            print(line.strip()[::-1])
finally:
    print("Finally Its done!")



